version: '3.9'
services:
  bot:
    build: .
    container_name: "${CONTAINER_NAME}"
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./sessions:/app/sessions
    command: python ./main.py
    env_file:
      - .env